---
title: "SVM"
output: html_notebook
---

```{r}
library(readr)
require(xgboost)
require(Matrix)
require(data.table)
require(caret)
require(mltools)
require(data.table)
require(progress)
library(e1071)


df <- read_csv("https://raw.githubusercontent.com/upadhyan/StudentSuccess/main/data/math_data_cleaned.csv")

drops <- c("X","G1","G2","G3", "Student_Score")
df <- df[ , !(names(df) %in% drops)]

por_data <- read_csv("https://raw.githubusercontent.com/upadhyan/StudentSuccess/main/data/por_data_cleaned.csv")

Y <- df$Student_Class - 1
X <- df[,names(df) != "Student_Class"]
dtypes <- sapply(X, class)
categorical_names <- names(dtypes[dtypes != "integer"])
numerical_names <- names(dtypes[dtypes == "integer"])
categorical <- X[categorical_names]
numerical <- X[numerical_names]
categorical <- as.data.table(lapply(categorical, as.factor))
categorical <- one_hot(categorical)
X = cbind(categorical, numerical)

partition = createDataPartition(
  Y,
  times = 1,
  p = 0.7,
  list = TRUE,
  groups = min(5, length(Y))
)
X_train = X[partition$Resample1,]
X_test = X[-partition$Resample1,]
Y_train = Y[partition$Resample1]
Y_test = Y[-partition$Resample1]

Y_train = factor(Y_train) 

train_data <- cbind.data.frame(X_train, Y_train)

Y_test = factor(Y_test) 

test_data <- cbind.data.frame(X_test, Y_test)

```

```{r}

svm_math <- svm(train_data$Y_train~., data=train_data,kernel = "radial", cross = 5) 

mathPred = predict(svm_math, newdata=X_test)
table(mathPred, Y_test)
CM = table(mathPred, Y_test)
accuracy = (sum(diag(CM)))/sum(CM) 
misclass_rate_svm <- 1 - accuracy
misclass_rate_svm



#set.seed(1)
#tune.out = tune(svm_math, Y_test~. , data = test_data , ranges = list(cost = c(0.1, 1, 10, 100, 1000), gamma = c(0.5, 1, 2, 3, 4)))
#summary(tune.out)



#########
#Por data
########


df <- read_csv("https://raw.githubusercontent.com/upadhyan/StudentSuccess/main/data/por_data_cleaned.csv") # por data

drops <- c("X","G1","G2","G3", "Student_Score")
df <- df[ , !(names(df) %in% drops)]

Y <- df$Student_Class - 1
X <- df[,names(df) != "Student_Class"]
dtypes <- sapply(X, class)
categorical_names <- names(dtypes[dtypes != "integer"])
numerical_names <- names(dtypes[dtypes == "integer"])
categorical <- X[categorical_names]
numerical <- X[numerical_names]
categorical <- as.data.table(lapply(categorical, as.factor))
categorical <- one_hot(categorical)
X = cbind(categorical, numerical)

partition = createDataPartition(
  Y,
  times = 1,
  p = 0.7,
  list = TRUE,
  groups = min(5, length(Y))
)
X_train = X[partition$Resample1,]
X_test = X[-partition$Resample1,]
Y_train = Y[partition$Resample1]
Y_test = Y[-partition$Resample1]

Y_train = factor(Y_train) 

train_data <- cbind.data.frame(X_train, Y_train)

Y_test = factor(Y_test) 

test_data <- cbind.data.frame(X_test, Y_test)

```

```{r}

svm_por <- svm(train_data$Y_train~., data=train_data, cross = 5) 

porPred = predict(svm_por, newdata=X_test)
table(porPred, Y_test)
CM = table(porPred, Y_test)
accuracy = (sum(diag(CM)))/sum(CM) 
misclass_rate_svm <- 1 - accuracy
misclass_rate_svm



#set.seed(1)
#tune.out = tune(svm_math, Y_test~. , data = test_data , ranges = list(cost = c(0.1, 1, 10, 100, 1000), gamma = c(0.5, 1, 2, 3, 4)))
#summary(tune.out)
